/*
Package tpm provides an interface to a TPM2.0 device in golang.

⚠️ THIS PACKAGE IS A WORK-IN-PROGRESS AND IS NOT CONSIDERED SAFE FOR PRODUCTION USE. DO NOT USE THIS PACKAGE WITH
ANY APPLICATION THAT INTERACTS WITH SENSITIVE DATA.
*/
package tpm
